### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by qishen** [VictorCoder123/shooting-game#1]
- [ ] Fix bugs when new player enters, but existing enemies are not updated.
- [ ] Tween player ships a little bit when they are hit and return to original point.
- [ ] Update scores properly.
- [ ] Set up game over state when player is dead.
- [ ] Add more weapons and reduce the speed of weapons.
